services:
  auth-db:
    image: postgres:latest
    container_name: bookstore_auth_db
    hostname: auth_db
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DBNAME}
      TZ: Europe/Sofia
    ports:
      - "5450:5432"
    volumes:
      - auth-bookstoredb-data:/var/lib/postgresql/data
    networks:
      - bookstore_network
  
  books-db:
    image: postgres:latest
    container_name: bookstore_books_db
    hostname: books_db
    environment:
      POSTGRES_USER: ${BOOKS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BOOKS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BOOKS_POSTGRES_DBNAME}
      TZ: Europe/Sofia
    ports:
      - "5451:5432"
    volumes:
      - books-bookstoredb-data:/var/lib/postgresql/data
    networks:
      - bookstore_network



volumes:
  auth-bookstoredb-data:
    driver: local
    name: auth-bookstoredb-data
  books-bookstoredb-data:
    driver: local
    name: books-bookstoredb-data

networks:
  bookstore_network:
    driver: bridge
    name: bookstore_network